matrix:
  include:
    - language: java
      dist: trusty
      install: true
      jdk:
        - openjdk8
        - openjdk11
      script:
        - ./gradlew :runner:verGJF
        # test is done in docker
        # - travis_wait ./gradlew :runner:test
      services:
        - docker
      before_install:
        - docker-compose build
        - docker-compose run --rm test

    - language: node_js
      node_js:
        - "10.15.0"
      before_script:
        - cd ui
      script:
        - yarn install && yarn test

