matrix:
  include:
    - language: java
      dist: trusty
      install: true
      jdk:
        - openjdk11
      script:
        - ./gradlew :runner:verGJF
        - travis_wait ./gradlew :runner:test

    - language: node_js
      node_js:
        - "10.15.0"
      before_script:
        - cd ui
      script:
        - yarn install && yarn test
      
